[package]
name = "polly-rs"
version = "0.1.0"
authors = ["ltlollo <ltlollo.it@gmail.com>"]

[dependencies]
image = "0.3.11"
libc = "0.1.8"
docopt = "0.6.69"
docopt_macros = "0.6.69"
rustc-serialize = "0.3.15"
